Implement button atom
cogito-study/alea pull request #3
Opened 2019-08-02 18:46 UTC by matepapp

2019-08-03 16:35 UTC, AdamBelakovics commented
Something is wrong with the tertiary button animation. Looks like it animates the border-width too, which seems odd to me. Maybe we should define animations for the desired css fields only.

2019-08-03 16:36 UTC, AdamBelakovics approved these changes

2019-08-03 16:37 UTC, AdamBelakovics requested changes
Something is wrong with the tertiary button animation. Looks like it animates the border-width too, which seems odd to me. Maybe we should define animations for the desired css fields only.

2019-08-05 09:12 UTC, matepapp commented
@AdamBelakovics thanks for the comment, I fixed the border spacing issue!

2019-08-05 09:49 UTC, balintkiraly approved these changes

2019-08-05 10:58 UTC, merged