Component input
cogito-study/alea pull request #46
Opened 2019-08-16 17:47 UTC by AdamBelakovics

Almost complete feature set

2019-08-20 08:05 UTC, matepapp requested changes

2019-08-20 08:05 UTC, matepapp commented on src/components/text-input/text-input.stories.tsx
> +export const wip_withIcon = () => (
ha mar nincs vele munka, akkor nem kell a `wip` szerintem

2019-08-20 08:05 UTC, matepapp commented on src/components/text-input/text-input.tsx
> +const IconContainer = styled.div`
ez szerintem eleg, ha ugy hasznaljuk a kodban, hogy 
```
<Flex flexWrap="wrap" pr={2} />
```

es akkor nem kell +1 indirekcio

2019-08-20 08:05 UTC, matepapp commented on .gitignore
> +eva-icons/
```suggestion
**/eva-icons/
```

2019-08-20 08:05 UTC, matepapp commented on src/atoms/icon/icon.tsx
> +const EmailFill = () => (
szerintem az Email-lel kapcsolatos dolgok keruljenek kulon fajlba, mondjuk `email.icon.tsx` neven. onnan exportaljuk majd ki az `EmailIcon` komponenst.

2019-08-20 08:05 UTC, matepapp commented on src/atoms/icon/icon.tsx
> +  filledIcon: ReactNode;
ide szerintem felesleges az Icon postfix, eleg annyi, hogy `filled` es `outlined`, kicsit tisztabb lesz az API

2019-08-20 08:05 UTC, matepapp commented on src/atoms/icon/icon.tsx
> +const EmailFill = () => (
ugyanitt nevkonvencio alapjan szerintem az `EmailFilled` es `EmailOutlined` jobb lenne, nem?

2019-08-20 08:05 UTC, matepapp commented on src/components/text-input/text-input.tsx
> +  align-items: center;
amiket tudunk hasznalni a `styled-system` alapjan, azokat szerintem mozgassuk at inkabb a propok koze. igy elso ranezesre

- align-items
- justify-content
- flex-direction
- background-color
- border-width
- border-style
- padding
- font-family
- max-width

es akkor valahogy igy nezne ki `<InputContainer alignItems="center" justifyContent="flex-end" .../>`

2019-08-20 08:05 UTC, matepapp commented on src/components/text-input/text-input.tsx
> +const StyledInput = styled.input<StyledInputProps>`
itt is a color, backgroundColor mehet props-bol

2019-08-20 08:05 UTC, matepapp commented on src/components/text-input/text-input.tsx
> +        <Paragraph color={theme.colors.error.normal} paragraphSize="small" marginTop="8px">
ne hasznaljunk sehol paddingra vagy marginra pixeleket. keressuk meg [a design system ahhoz tartozo spacing erteket](https://alea.cogito.study/?path=/story/token-space--space-2). `marginTop={2}`

2019-08-21 15:28 UTC, AdamBelakovics commented on src/components/text-input/text-input.tsx
> +  align-items: center;
Szerintem ezt hagyjuk

2019-08-21 16:08 UTC, matepapp approved these changes
![](https://media.giphy.com/media/k0CJuMw9h7m3S/giphy.gif)

2019-08-21 16:23 UTC, merged